### ISSUE TITLE
Do you have a roadmap?

### ISSUE THREAD

**Issue by guiseek** [11ty/eleventy-community#17]
I was wondering if you have plans to support typescript, as I saw that they are using pure javascript and don't have an @types package

I ask this why I thought of writing an nx plugin so that I and others use eleventy in monorepos

**Comment by zachleat** [comment]
Please file enhancement requests here: https://github.com/11ty/eleventy/issues We have this enhancement queue which has the most popular community-requested features https://github.com/11ty/eleventy/issues?q=label%3Aneeds-votes+sort%3Areactions-%2B1-desc+label%3Aenhancement
