### ISSUE TITLE
Browsersync doesn't hot reload js or css files

### ISSUE THREAD

**Issue by brandonalexandertong** [11ty/eleventy-community#18]
Apologies for what I'm sure is quite simple, but I'm using eleventy and webpack together based on [this](https://statickit.com/guides/eleventy-webpack) guide, and when I update the css or js, there is no hot reload. 

I know that browsersync is watching, because when I change the index.md file it hot reloads the browser, but for some reason this doesn't work with js or css. When I make changes to these files, webpack updates, and it is built, but no reload. 

Anyone know how to tell it to watch those files?

**Comment by kylesloper** [comment]
Any updates on this?

**Comment by siakaramalegos** [comment]
@kylesloper @brandonalexandertong this repo is actually for community building not issues or bugs. Try the main repo or join the discord group https://discord.gg/BAXFMW7aVm

**Comment by kylesloper** [comment]
Oops didn't see that there. I'll pop over to the discord now 😊

**Comment by zachleat** [comment]
Thanks y’all
