### ISSUE TITLE
Eleventy Community Conduct Expectations

### ISSUE THREAD

**Issue by zachleat** [11ty/eleventy-community#2]
Gathering some folks that want to be involved with some proactive work around this tweet: https://twitter.com/zachleat/status/1165972364045238272

We want to be incredibly up front about what is expected of behavior in our community from the get-go.

**Comment by dhoman** [comment]
I don't think you can prevent bad actors from utilizing your project. HOWEVER, you might be able to put something in the TOS of the project to discourage eleventy from being showed / talked about at conferences that don't have welcoming conference rules.

But to enforce it you'd probably have to check what talks get posted at conferences and see if it's a bad community or bad actor presenting and address the issues one by one.

Pros: might get more conferences to be proactive or reflect on their community guidelines
Cons: it'd be a good amount of work

Then eleventy could have a page for articles and talks and link to only the ones by good actors or at welcoming communities

I do like this idea, I'm just trying to expand on the idea. But yeah it's a tough problem, but I like where you are going with it.

Edit: I reread your comment and i'd be willing to help in whatever way I can

**Comment by zachleat** [comment]
Specifically we also need to look at https://github.com/11ty/eleventy/blob/master/CODE_OF_CONDUCT.md and revise per community standards, not just project participant standards.

**Comment by Ryuno-Ki** [comment]
@zachleat You already have a community!

Question is whether you want to give it more structure.
I could see these jobs (perhaps mapped to GitHub teams):

- Triager: making sure, enough information is available to enable work on tickets. Spotting duplicates. Crosslinking with similar issues.
- Documentors: Technical writers (APIs, function signatures and so on) or usage guides
- Coders: Moving the codebase forward. Perhaps you could declare code owners here.
- Evangelists: Making the project known via talks, podcasts, guest posts, meetups etc.

**Comment by zachleat** [comment]
https://twitter.com/eleven_ty/status/1235323006911733762

**Comment by DirtyF** [comment]
> Respect the CoC — Frank T.J. Mackie (Magnolia)

**Comment by zachleat** [comment]
Closing this one, we have this linked up very prominently in our nav sidebar https://www.11ty.dev/docs/code-of-conduct/
