### ISSUE TITLE
Community support (chat, slack, forum, etc)

### ISSUE THREAD

**Issue by octoxalis** [11ty/eleventy-community#4]
After comparing Hugo and Eleventy I think the later really deserves a wider adoption by those in search of a fine static site generator as I'm.
However there's no forum or Stack Exchange community to find some help. It would be nice to create one, don't you think so?

**Comment by zachleat** [comment]
https://medium.com/@Pier/vue-js-the-good-the-meh-and-the-ugly-82800bbe6684 reminded me of this discussion:

> This trend of using chats for questions is plaguing open source projects and I think it needs to end. There is no collective learning anymore.

**Comment by danielstaleiny** [comment]
I think keeping it in github is the best thing, encourage conversation in README and make people ask even stupid question here in issues. :))

**Comment by octoxalis** [comment]
[11tyTips](https://11tytips.netlify.com) now not far from its public opening. A few tips are still work in progress!

Some feedback about content and presentation would be invaluable if you have a few minutes to review what is now online.

**Comment by danielstaleiny** [comment]
@octoxalis Where did Matrix part name come from ? 

I was working on some boilerplate as well, but the structure is a bit confusing so I am thinking about re-thinking it. You can have a look here https://github.com/danielstaleiny/parceleventy

**Comment by octoxalis** [comment]
Well, *matrix* directory is another name for *_includes*, more meaningful,
IMHO, because you guess this is where the work is being done. That's all.

BTW you now have a dedicated site to fork your own repo of 11tyTips: it's
called *11tyFrame* and it gives you in its initial pages the instructions
to install a new site deployed by Netlify (I shall later automate this
process with a "deploy to Netilify" button).

Please, let me know if you find something unclear in 11tyFrame site.

**Comment by gweatherson** [comment]
I'd love a slack channel as well.

**Comment by nhoizey** [comment]
I agree about the separation of concerns, and I believe StackOverflow would be a good fit for the support part, to help other use Eleventy.

**Comment by zachleat** [comment]
Just to organize the options that have been suggested so far:

- [x] GitHub Issues 
- [ ] GitHub Discussions
- [ ] Slack
- [ ] https://spectrum.chat/
- [ ] https://indieweb.org/WebSub
- [ ] Gitter.im
- [ ] IRC
- [ ] https://matrix.org/
- [ ] https://www.discourse.org/
- [ ] Telegram Group
- [ ] Telegram Channel

**Comment by octoxalis** [comment]
GitHub Issues are great because everything stays inside Eleventy repo.

In the [JAMstackTheme](https://jamstackthemes.dev/theme/11tyframe/) I'm just publishing and its companion site [11tyTips](https://11tytips.netlify.com), I'm experimenting the comments system by [utteranc.es](https://utteranc.es) using GitHub Issues to store comments. It's so new that I have no feedback yet.

However, what about an **Eleventy site** with such a comment system and a search API to retrieve issues matching search keywords?

**Comment by dixonge** [comment]
My opinion:

I like using GitHub Issues for support - as long as @zachleat doesn't mind having to deal with more trivial issues, which we users will *definitely* put there. But...

I *hate* the idea of trying to ask non-bug, not-really-direct questions there. Some things aren't really support issues. Like today, I am realizing I need to expand my knowledge of the Node universe, but only specific to things that are related to eleventy. (I'm retired, I'm not going to learn Node and javascript beyond setting up my few blogs.) So it would seem really weird to ask about npm vs npx in the 11ty github repo. Equally as strange to ask about tailwind/postcss/purgecss there. But there *is* a place I would like to ask this question...

In an 11ty community! A place where both experienced and newb users exchange info. If @zachleat wants to have superadmin rights, great, but I don't think such a forum should expect his presence or require any time from him at all. I agree that *chat* is a bad format for this, and wikis are very one-way. But a *forum* is perfect. Almost all my favorite places for this type of community exchange are run using Discourse. 

So why can't there be a Discourse forum? It seems, to me, to be the ideal format for us users to share amongst ourselves.

**Comment by octoxalis** [comment]
Well, the "cheaper" **Discourse** plan is **100$/month**: not sure it's worth the price for a JAMstack site community! GitHub Issues are for free and it has all the power needed.

I definitely would vote for **Issues**

**Comment by danielstaleiny** [comment]
Let's just treat github issues as discourse, there is nothing that I am aware of that discourse provide over this method.  I would also say that discourse is not super convenient for newcomers. ( maybe it just me. I am just used to github too much, compare to new discourse.)

**Comment by dixonge** [comment]
> Well, the "cheaper" **Discourse** plan is **100$/month**: not sure it's worth the price for a JAMstack site community! GitHub Issues are for free and it has all the power needed.

Holy crap! OK, well nvm then :(

**Comment by charlesroper** [comment]
It's only $100 if you go with Discourse's own managed hosting. It's open source and can be easily installed on your own host ([see here](https://github.com/discourse/discourse/blob/master/docs/INSTALL-cloud.md)). I run a small Discourse forum and it costs $6 per month for hosting & backups on Digital Ocean. Once it's installed, keeping it "maintained" is literally logging-in to the admin control panel and clicking "upgrade all" whenever I get an email telling me there's an update. They've really done a splendid job on making it easy to update.

That said, if you're going to use GitHub Issues as a forum (which doesn't seem unreasonable, considering the audience), is to make it clear from the main site that is what is going on and provide a link. I found this thread looking for a support forum and would never have thought to use GH issues. Also perhaps have a separate repo (e.g., this one!) for support with its own set of labels for categorisation. At the moment, there's the education label which covers all support questions, whereas an expanded set of labels might be helpful (see the [Hugo forum categories](https://discourse.gohugo.io/categories), for example).

**Comment by huphtur** [comment]
Looks like GitHub is experimenting with a "[Discussions](https://github.com/zeit/next.js/discussions)" tab...

**Comment by dixonge** [comment]
Yeah, just saw that. Best of both worlds? I like it...

**Comment by DirtyF** [comment]
@nat about the Discussions beta feature on HN:

> You can mark which comment answers a question, and comments can be voted.

This would ease the search for commonly asked questions.❤️ 

> We're going to try it out in a few interested communities, and if people like it, we'll make it available GitHub-wide. It's early, though, and we want a chance to learn what works and iterate on a smaller scale before introducing it to everyone. 

@zachleat Would you be willing to move all the current `education` labeled issues into the discussions tab?

**Comment by octoxalis** [comment]
Github Discussions tab looks promising and has my preference because everything stays in a unique environment.

BTW, to broaden this debate, it would be nice to have a direct link to this Community support repository on Eleventy main Github page.

**Comment by whaleen** [comment]
> From previous experience, having a public forum helps the core team focus on the issues and not the education part. It's a matter of signal/noise in issues, when it becomes not manageable, then maybe it will be time to move those conversations elsewhere.

>BTW, to broaden this debate, it would be nice to have a direct link to this Community support repository on Eleventy main Github page.

If the eleventy-community repo can be the 'public forum', and if in it, it's true that there is no such thing as a "dumb question", then it would work for me. I have plenty of dumb questions I hesitate to post in the main repo. 

A regular old forum might really serve the community well though. I'd really like to see one. I'd especially like to see one moderated by the core 11ty contributors. 

It could be built from phpbb and hosted on webblaze.biz for all I care. Literally just have people post questions in categories.

**Comment by whaleen** [comment]
btw webblaze.biz is available if you want to get this show on the road. :)

**Comment by Engine44** [comment]
With 11ty what are the best options to import data?  Thanks.

**Comment by whaleen** [comment]
@Engine44 to 'import', I've been doing:
`curl 'https://someplace.com/data_i_want.json' -o _data/imported.json`

If it's possible for you access your data as JSON or to format it as such, then this should do the trick. Obviously, you don't need to get it from a remote URL like above as you can just create the file manually and place it in the _data directory. The _data directory is where 11ty by default expects your data files to be. If it doesn't exist in your project then you can create it and 11ty will automatically recognise it. 

There are other data formats you can use besides JSON.

Look at the 11ty docs on how data files can be utilised once they are in the _data directory of an 11ty project: 
https://www.11ty.dev/docs/data-global/

Depending on the structure of your JSON, or other type of data file, it can be a little tricky to process it into something usable but if you look at all the 11ty starter templates you can see it being done in a wide variety of ways. Check out people's _data folders and see how they make use of the data files in their templates.

**Comment by Engine44** [comment]
> @Engine44 to 'import', I've been doing:
> `curl 'https://someplace.com/data_i_want.json' -o _data/imported.json`
> 
> If it's possible for you access your data as JSON or to format it as such, then this should do the trick. Obviously, you don't need to get it from a remote URL like above as you can just create the file manually and place it in the _data directory. The _data directory is where 11ty by default expects your data files to be. If it doesn't exist in your project then you can create it and 11ty will automatically recognise it.
> 
> There are other data formats you can use besides JSON.
> 
> Look at the 11ty docs on how data files can be utilised once they are in the _data directory of an 11ty project:
> https://www.11ty.dev/docs/data-global/
> 
> Depending on the structure of your JSON, or other type of data file, it can be a little tricky to process it into something usable but if you look at all the 11ty starter templates you can see it being done in a wide variety of ways. Check out people's _data folders and see how they make use of the data files in their templates.

Thank you.  Can you use GraphQL?

**Comment by whaleen** [comment]
@Engine44 
[https://www.webstoemp.com/blog/headless-cms-graphql-api-eleventy/](https://www.webstoemp.com/blog/headless-cms-graphql-api-eleventy/)

**Comment by Engine44** [comment]
> @Engine44
> https://www.webstoemp.com/blog/headless-cms-graphql-api-eleventy/

Thanks for your response.  To go into more depth:  I have developed a few Wordpress sites for clients.  They like WP and don't want to change.  So I would like to use WP as a headless CMS with Eleventy.  Currently there are 2 GraphQL associated WP plugins:  WPGraphQL and WPGraphiQL. Both were developed with the intention of connecting WP to Gatsby.  Not sure if they can be used with Eleventy.  Have you heard of them?

**Comment by Engine44** [comment]
> @Engine44
> https://www.webstoemp.com/blog/headless-cms-graphql-api-eleventy/

Thanks

**Comment by Engine44** [comment]
I am working through the tutorial "MAKING A SIMPLE WEB SITE WITH THE SIMPLEST STATIC SITE GENERATOR, LEVEL 1".  I am at the "MAKE IT DATA DRIVEN" section.  I am copy/pasting the code where "front matter"  is created.  Which index.html file is it supposed to be pasted to?  When I try to run it I get error: **Cannot GET /**. Thanks.

**Comment by binyamin** [comment]
@octoxalis 11ty discord is a thing now. FYI. Does this solve the issue? https://discord.gg/GBkBy9u

**Comment by dixonge** [comment]
> @octoxalis 11ty discord is a thing now. FYI. Does this solve the issue? https://discord.gg/GBkBy9u

It's chat, better than nothing I guess. Still far inferior to fora, since not *everyone* has their computer on 24/7. Plus I just don't like Discord.

**Comment by zachleat** [comment]
Going to close this one, super late. We have an official discord now. https://www.11ty.dev/blog/discord/
