### ISSUE TITLE
[Question] Any idea how to render a side by side diff of two **different** files?

### ISSUE THREAD

**Issue by tayelno** [11ty/eleventy-community#7]
How would you guys go about rendering a diff between two different files side by side sort of like git diff using eleventy ? I am sure there is a library can do just that but I can't find any ...

I know this is a general question in the JAMStack field and not specifically related to **eleventy**, so feel free to close it if you want to, but I would appreciate the help.

**Comment by zachleat** [comment]
Any reason this was closed? Did you figure it out?

**Comment by tayelno** [comment]
Nope just thought it was not elaborate enough and did not have time to re-write it 😅
